services:
  - type: web
    name: bablu-transcriber
    env: python
    buildCommand: "./build.sh && pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port 10000 --server.enableCORS false"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
